app.py
# -*- coding: utf-8 -*-
import os
import random
import nltk
nltk.data.path.append('./nltk_data/')

from werkzeug.routing import BaseConverter

import flask
from flask import session, render_template
from flask.ext.compress import Compress

from blueprints.pages import pages

import pynamegen


app = flask.Flask(__name__)
Compress(app)  # enabling gzip compression

app.secret_key = 'kapsd-qjkjz xvscv[widf d[f0iya d09209 -S{PS]q ] } S}Q }S{S Q{}S Fsf]q } FS}{ F}Q{Q}W{R}(]xAFaP{OXCL:'
app.config.update(HTTP_PREFIX='http://')


basic_words = nltk.corpus.words.words('en-basic')
all_words = nltk.corpus.words.words('en')
random.shuffle(all_words)
app.config['words'] = all_words[:300] + basic_words


_names = pynamegen.Names(pynamegen.EN_ALPHABET)
app.config['names'] = _names.generator(use_enchant=False, use_words=True, words=app.config['words'])

app.register_blueprint(pages)

if __name__ == '__main__':
    app.config.update(DEBUG=True)
    app.debug = True
    app.run()

blueprints/pages.py
# -*- coding: utf-8 -*-

from flask import redirect, Blueprint, render_template, current_app, send_from_directory,request, abort, redirect, url_for, make_response, Response, jsonify
import pynamegen


pages = Blueprint('pages', __name__)

@pages.route('/')
def home():
    variants = []
    for i in range(0,10):
        variants += [[word.title() for word in current_app.config['names'].next().split(u' ')]]

    return render_template('index.html', variants=variants)

@pages.route('/names/', methods=['GET'])
def generate():
    num_words = int(request.args['num_words'])
    max_symbols = int(request.args.get('minmax_words', 6))
    true_random = request.args.get('true_random', 'off') == 'on'
    use_numbers = request.args.get('use_numbers', 'off') == 'on'

    character_set = pynamegen.EN_ALPHABET
    if use_numbers:
        character_set += pynamegen.DIGITS

    _names = pynamegen.Names(character_set).generator(num_words=num_words, max_symbols=max_symbols, use_enchant=False, 
        use_words=not true_random, words=current_app.config['words'])


    variants = []
    for i in range(0,20):
        variants += [[word.title() for word in _names.next().split(' ')]]

    return render_template('generate.html', variants=variants)

pynamegen/__init__.py
# -*- coding: utf-8 -*-
import random

EN_ALPHABET = map(chr, range(97, 123))
DIGITS = map(str, range(0, 9))


class Names(object):
    def __init__(self, character_set=tuple(DIGITS + EN_ALPHABET)):
        self.characters = character_set

    def generator(self, num_words=2, min_symbols=3, max_symbols=6, use_words=True, words=(), use_enchant=True, enchant_locale='en_US', separator=' '):
        if use_enchant:
            import enchant
            d = enchant.Dict(enchant_locale)
        elif use_words:
            words_len = len(words)
        else:
            d = None

        characters_length = len(self.characters)

        while True:
            result = []

            for word_i in range(0, num_words):
                word_len = random.randint(min_symbols, max_symbols)
                word = u''

                if use_words:
                    dictionary = filter(lambda w: len(str(w)) == word_len, words)
                    # dictionary = ['a', 'b']
                    word = dictionary[random.randint(0, len(dictionary) - 1)]
                else:
                    for i in range(0, word_len):
                        word += self.characters[random.randint(0, characters_length-1)]
                    
                    if d:
                        suggestions = d.suggest(word)
                        if suggestions:
                            word = str(suggestions[random.randint(0, len(suggestions) - 1)])

                result += [word]

            yield separator.join(result)


if __name__ == '__main__':
    names = Names()
    g = names.generator()
    for i in range(0, 10):
        print g.next()

templates/generate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="keywords" content="koding, team name, generator"/>
    <meta name="description" content="Create cool name for your team using Koding Global Hackathon Team names generator! It packed with lots of features and completely OpenSource."/>

    <title>Welcome to Koding Global Hackathon Team Name Generator</title>
</head>
<body>
<div class="container">
 		
		<div class="row">
        <div class="col-md-12 text-center">
        		<h2>Voila!</h2>
        		<div class="text-center">
            {% for variant in variants %}
              <a style=" padding-right: 20px; font-size: 22px; color: " href="https://twitter.com/home?status=Go%20team%20{% for word in variant%}%23{{ word }}{% endfor %}%20for%20@koding%20%23hackathon%20https://koding.com/Hackathon">{% for word in variant%}{{ word }}&nbsp;{% endfor %}</a>
            {% endfor %}    
            </div>
        </div>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-12 text-center">

        <button type="button" class="btn btn-default" onclick="javascript: document.location.href='https://vast-cove-6783.herokuapp.com/';">&larr; Back to Home</button>
    		<button type="button" class="btn btn-success" onclick="javascript: document.location.reload();">Generate again!</button>
        </div>
		</div>

  			<div class="col-md-3 hidden-xs"></div>
  		</div>

  		 <div class="row">
        <div class="col-md-12 text-center">
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Koding Global Hackathon  Team Name Generator -->
					<ins class="adsbygoogle"
					     style="display:block"
					     data-ad-client="ca-pub-9423687387443767"
					     data-ad-slot="1999433626"
					     data-ad-format="auto"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
        </div>	
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57055666-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="keywords" content="koding, team name, generator"/>
    <meta name="description" content="Create cool name for your team using Koding Global Hackathon Team names generator! It packed with lots of features and completely OpenSource."/>

    <title>Welcome to Koding Global Hackathon Team Name Generator</title>


</head>
<body>


<div class="container">
 		<div class="row">
      <div class="col-md-6 text-center">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- Koding Global Hackathon  Team Name Generator -->
				<ins class="adsbygoogle"
				     style="display:block"
				     data-ad-client="ca-pub-9423687387443767"
				     data-ad-slot="1999433626"
				     data-ad-format="auto"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
      </div>	
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
        		<h1>Koding Global Hackathon Team Name Generator</h1>
        		<h2>Create cool unique name for your coding team!</h2>
        </div>
    </div>

		<div class="row">
        <div class="col-md-12 text-center">
        		<h2>Look at this great sample<br/> truly unique randomized team names!</h2>
        		<div class="text-center">
        		{% for variant in variants %}
        			<a style=" padding-right: 20px; font-size: 22px; color: " href="https://twitter.com/home?status=Go%20team%20{% for word in variant%}%23{{ word }}{% endfor %}%20for%20@koding%20%23hackathon%20https://koding.com/Hackathon">{% for word in variant%}{{ word }}&nbsp;{% endfor %}</a>
        		{% endfor %}		
        		</div>
        </div>
    </div>

    <div class="row">
    	<div class="col-md-3 hidden-xs"></div>
    	<div class="col-md-6 col-xs-12">
    		<h2>...or generate your own!</h2>
    			<div class="well">
        		<form action="{{ url_for('pages.generate') }}" method="GET" class="form">

	        		<div class="form-group">
						    <label forid="id_numwords">Number of words to use</label>
						    <input type="number" id="id_numwords" name="num_words" value="2" class="form-control">
						  </div>
						  <div class="form-group">
						    <label forid="id_minmaxlen">Max length of words</label>
						    <input type="range" id="id_minmaxlen" min="1" max="10" step="1" defaultValue="6" name="minmax_words">
						  </div>
						  <div class="form-group">
						    <input type="checkbox" id="id_truerandom" name="true_random" checked="checked"> Truely random?</input>
						  </div>
						  <div class="form-group">
						    <input type="checkbox" id="id_usenumbers" name="use_numbers"> Use numbers?</input>
						  </div>

	        		<button type="submit" class="btn btn-success">Go Generate!</button>
        		</form>
        	</div>
  			</div>

  			<div class="col-md-3 hidden-xs"></div>
  		</div>

  		 <div class="row">
        <div class="col-md-12 text-center">
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Koding Global Hackathon  Team Name Generator -->
					<ins class="adsbygoogle"
					     style="display:block"
					     data-ad-client="ca-pub-9423687387443767"
					     data-ad-slot="1999433626"
					     data-ad-format="auto"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
        </div>	
    </div>


   


</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">


            <h2>About this site</h2>

            <p>I'm developer who take part in World's First Global Virtual Hackathon announced by <a href="http://koding.com">Koding.com</a>. My name is <a href="https://twitter.com/v_ignatyev">Vladimir</a> and I built this pretty site for 2 hours of coding while trying to give the name for my team.</p>
            <p>The site is hosted at <a href="http://herokuapp.com">Heroku</a> and made with Python programming language using <a href="http://flask.pocoo.org/docs/0.10/api/">Flask framework</a>.</p>
            <p>The generation algorithm uses <a href="http://www.nltk.org/">Natural Language Toolkit</a> for english words dictionary. The code generating all this stuff is available <a href="https://github.com/vladignatyev/kodingteamname">on GitHub</a></p>
        </div>


        <div class="col-md-6">
          <h2>About First Global Koding Hackathon</h2>
          <p>Awesome guys from Koding.com created event called World’s First Global Virtual Hackathon. </p>
          <p>As they say: <cite>This event is intended to connect developers across the globe and get them to code together irrespective of their locations. You will problem solve and build with old or new team members and try to win!</cite> </p>
          <p>Go to <a href="https://koding.com/Hackathon">Official World's First Global Hackathon page</a> to learn more and join/create teams for building DIY 48h-made products using topmost software technologies and APIs.</p>
				</div>
    </div>

    <div class="row">
        <div class="col-md-12" style="padding-top:16px;">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
						<!-- Koding Global Hackathon  Team Name Generator -->
						<ins class="adsbygoogle"
						     style="display:block"
						     data-ad-client="ca-pub-9423687387443767"
						     data-ad-slot="1999433626"
						     data-ad-format="auto"></ins>
						<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
						</script>
        </div>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57055666-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>